name: prise-backwards-compatability

on: [push, pull_request]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      # Copies all compatability plugins to integration test directory
      - run: mkdir -p src/Prise.Tests.Integration/_dist
      - run: cp -r src/Prise.Tests.Integration/compatibility/netstandard2.1/PluginA src/Prise.Tests.Integration/_dist
      - run: cp -r src/Prise.Tests.Integration/compatibility/netstandard2.1/PluginB src/Prise.Tests.Integration/_dist
      - run: cp -r src/Prise.Tests.Integration/compatibility/netstandard2.0/PluginC src/Prise.Tests.Integration/_dist
      
      - name: Restore IntegrationTestsHost
        run: dotnet restore src/Prise.Tests.Integration/Prise.IntegrationTestsHost/Prise.IntegrationTestsHost.csproj

      - name: Test Prise.IntegrationTests
        run: dotnet test src/Prise.Tests.Integration/Prise.IntegrationTests/Prise.IntegrationTests.csproj