name: prise-integration-tests

on: [push, pull_request]

jobs:
  run-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      # Publishes all plugins to publish directory
      - run: dotnet publish src/Prise.Tests.Integration/IntegrationTestsPlugins/PluginA/PluginA.csproj -o ~/publish/PluginA
      - run: dotnet publish src/Prise.Tests.Integration/IntegrationTestsPlugins/PluginB/PluginB.csproj -o ~/publish/PluginB
      - run: dotnet publish src/Prise.Tests.Integration/IntegrationTestsPlugins/PluginC/PluginC.csproj -o ~/publish/PluginC

      # Copies all published plugins to integration test directory
      - run: mkdir -p src/Prise.Tests.Integration/_dist
      - run: cp -r ~/publish/PluginA src/Prise.Tests.Integration/_dist
      - run: cp -r ~/publish/PluginB src/Prise.Tests.Integration/_dist
      - run: cp -r ~/publish/PluginC src/Prise.Tests.Integration/_dist

      - name: Restore IntegrationTestsHost
        run: dotnet restore src/Prise.Tests.Integration/Prise.IntegrationTestsHost/Prise.IntegrationTestsHost.csproj

      - name: Test Prise.IntegrationTests
        run: dotnet test src/Prise.Tests.Integration/Prise.IntegrationTests/Prise.IntegrationTests.csproj