name: prise-unit-test-samples-plugins

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
        
    - name: Test Samples
      run: dotnet test samples/Tests/Tests.sln -f net6.0